#!/usr/bin/expect
set timeout 10
spawn ./poky-musl-x86_64-meta-toolchain-cortexa57-qemuarm64-toolchain-3.3.1.sh
expect "Enter target directory for SDK (default: /opt/poky/3.3.1):\r" 
send -- "./clang_sdk\r"
expect "You are about to install the SDK to \"/home/\$HOME/tla/tc_dir/sdk/clang_sdk\". Proceed\[Y/n\]?\r"
send -- "y\r"
set timeout 100
expect "SDK has been successfully set up and is ready to be used\r"

